server:
 port: 80
cors:
  originPatterns: http://localhost:8080,http://localhost:3000,https://erudio.com.br, http://localhost:3000
file:
   upload-dir: /code/UploadDir
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rest-with-spring-boot-and-java-erudio.cf0w8y4asrm3.sa-east-1.rds.amazonaws.com:3306/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
    username: docker
    password: fabio123
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  servlet:
  multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 200MB
      max-request-size: 215MB
springdoc:
  pathsToMatch:
    - /auth/**
    - /api/**/v1/**
  swagger-ui:
    use-root-path: true